spring:
  application:
    name: nacos-server-1
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        group: DEFAULT_GROUP
        file-extension: yaml
        import-check:
          enabled: false
      discovery:
        server-addr: 127.0.0.1:8848,127.0.0.1:8858,127.0.0.1:8868
        service: nacos-cluster
        cluster-name: NJ

server:
  port: 8848
