server:
  port: 15001   # 每个模块需设置唯一端口，如8081、8082等
spring:
  application:
    name: service-consumer-1  # 或 service-consumer-1 等，名称用于服务注册时标识
  main:
    allow-bean-definition-overriding: true
  cloud:
    loadbalancer:
      ribbon:
        enabled: false  # 关闭 Ribbon 相关配置，使用Spring Cloud LoadBalancer
      # 默认使用轮询策略，无需配置

# 设置Feign客户端访问路径
service-provider-1-url:

eureka:
  instance:
    prefer-ip-address: true
    instance-id: "${spring.cloud.client.ip-address}:${server.port}"
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
  client:
    service-url:
      defaultZone: "http://eurekaServer18000:18000/eureka/,http://eurekaServer18001:18001/eureka/,http://eurekaServer18002:18002/eureka/"
