#spring:
#  main:
#    allow-bean-definition-overriding: true
#  cloud:
#    loadbalancer:
#      ribbon:
#        enabled: false
#
#eureka:
#  instance:
#    prefer-ip-address: true
#    lease-renewal-interval-in-seconds: 5
#    lease-expiration-duration-in-seconds: 15
#  client:
#    service-url:
#      defaultZone: "http://eurekaServer18000:18000/eureka/,http://eurekaServer18001:18001/eureka/,http://eurekaServer18002:18002/eureka/"
#
#resilience4j:
#  circuitbreaker:
#    instances:
#      circuitBreakerA:
#        failureRateThreshold: 30
#        slidingWindowType: TIME_BASED
#        slidingWindowSize: 10
#        minimumNumberOfCalls: 5
#        waitDurationInOpenState: 5000
#        permittedNumberOfCallsInHalfOpenState: 3
#        registerHealthIndicator: true
#        automatic-transition-from-open-to-half-open-enabled: true
#        event-consumer-buffer-size: 5
#        recordExceptions:
#          - java.net.ConnectException
#          - java.io.IOException
#          - java.net.SocketException
#        ignoreExceptions: []
#      circuitBreakerB:
#        failureRateThreshold: 50
#        slowCallRateThreshold: 30
#        slowCallDurationThreshold: 2000
#        slidingWindowType: TIME_BASED
#        slidingWindowSize: 10
#        minimumNumberOfCalls: 5
#        waitDurationInOpenState: 5000ms
#        permittedNumberOfCallsInHalfOpenState: 3
#        registerHealthIndicator: true
#        automatic-transition-from-open-to-half-open-enabled: true
#        event-consumer-buffer-size: 5
#        record-exceptions:
#          - java.net.ConnectException
#          - java.io.IOException
#          - java.net.SocketException
#        ignore-exceptions: []
#  bulkhead:
#    instances:
#      bulkheadService:
#        maxConcurrentCalls: 10
#        maxWaitDuration: 20ms
#  ratelimiter:
#    instances:
#      rateLimiterService:
#        limitRefreshPeriod: 2s
#        limitForPeriod: 5
#        timeoutDuration: 1s
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#  endpoint:
#    health:
#      show-details: always
#  health:
#    circuitbreakers:
#      enabled: true
#    ratelimiters:
#      enabled: true
#
#greeting:
#  message: "你好，配置来自 Config Server (Git)！专门为 service-consumer-1 定制。"
#  from: "Git仓库-lab5/service-consumer-1.yml"
spring:
  main:
    allow-bean-definition-overriding: true
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
  client:
    service-url:
      defaultZone: "http://eurekaServer18000:18000/eureka/,http://eurekaServer18001:18001/eureka/,http://eurekaServer18002:18002/eureka/"

greeting:
  message: "你好，已经更新好的配置来自 Config Server (Git)！专门为 service-consumer-1 定制。"
  from: "Git仓库-lab5/service-consumer-1.yml"