spring:
  application:
  # name: service-provider-1 # spring.application.name 通常在 bootstrap 中定义，config server 根据它查找配置，这里可以省略或注释掉
  # 如果在 bootstrap.yml 中定义了 spring.application.name，则 Config Server 会自动根据它查找，这里的文件名 service-provider-1.yml 已经表明了它是为谁准备的。
  # 如果要在此处也写上，请确保与 bootstrap.yml 中的一致。

eureka:
  instance:
    prefer-ip-address: true
    # instance-id: "${spring.cloud.client.ip-address}:${server.port}" # 此配置依赖于 server.port，建议在 bootstrap.yml 中配置，或让 Eureka 自动生成
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
  client:
    service-url:
      defaultZone: "http://eurekaServer18000:18000/eureka/,http://eurekaServer18001:18001/eureka/,http://eurekaServer18002:18002/eureka/"

# 在这里添加 service-provider-1 和 service-provider-2 共享的其他配置
# 例如，它们可能连接到相同的数据库，或者有其他共同的业务参数
# message: "Hello from config server for service-provider-1 cluster!"