server:
  port: 9000

spring:
  application:
    name: service-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: service-provider-1
          uri: lb://service-provider-1
          predicates:
            - Path=/provider1/**
          filters:
            - StripPrefix=1
        - id: service-consumer-1
          uri: lb://service-consumer-1
          predicates:
            - Path=/consumer1/**
          filters:
            - StripPrefix=1

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://eurekaServer18000:18000/eureka/,http://eurekaServer18001:18001/eureka/,http://eurekaServer18002:18002/eureka/
    register-with-eureka: true
    fetch-registry: true

# 其他配置保持不变...